name: flutter_debug_overlay
description: Flutter package for implementing a debug overlay in your app, providing features like log viewers, HTTP request inspectors, and customizable widgets for easy debugging.
version: 0.1.0
repository: "https://github.com/Bungeefan/flutter_debug_overlay"

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.0
  package_info_plus: ^3.0.3
  device_info_plus: ^8.1.0
  split_view: ^3.2.1

  multi_long_press_gesture_recognizer: ^0.0.1
  flutter_json: ^0.0.1

  # Used to provide interceptors and adapters
  http: ^0.13.5
  http_parser: ^4.0.2
  dio: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
  uses-material-design: true
