name: flutter_debug_overlay
description: Flutter package for implementing a debug overlay in your app, providing features like log viewers, HTTP request inspectors, and customizable widgets for easy debugging.
version: 0.1.9
repository: "https://github.com/Bungeefan/flutter_debug_overlay"
topics:
  - debug
  - http
  - logging
  - overlay
  - inspector

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.0
  package_info_plus: '>=4.0.2 <9.0.0'
  device_info_plus: '>=8.0.0 <12.0.0'
  split_view: ^3.2.1

  multi_long_press_gesture_recognizer: ^0.0.1
  flutter_json: ^0.0.1

  # Used to provide interceptors and adapters
  http: ^1.0.0
  http_parser: ^4.0.2
  dio: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
  uses-material-design: true
